//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChkListCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Roles()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idRol { get; set; }
        public System.Guid UuidRol { get; set; }
        public string NombreRol { get; set; }
        public System.DateTime FG { get; set; }
        public string UG { get; set; }
        public Nullable<System.DateTime> FM { get; set; }
        public string UM { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public string UB { get; set; }
        public bool ST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
