//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChkListCursos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChkListCursosEntities : DbContext
    {
        public ChkListCursosEntities()
            : base("name=ChkListCursosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<cat_Area> cat_Area { get; set; }
        public virtual DbSet<cat_Roles> cat_Roles { get; set; }
        public virtual DbSet<Certificado> Certificado { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<CursoXempleado> CursoXempleado { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Instructor> Instructor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Verificador> Verificador { get; set; }
    }
}
