//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChkListCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoXempleado
    {
        public int idCursoXempleado { get; set; }
        public System.Guid UuidCursoXempleado { get; set; }
        public System.Guid UuidCurso { get; set; }
        public System.Guid UuidEmpleado { get; set; }
        public System.Guid UuidInstructor { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FG { get; set; }
        public string UG { get; set; }
        public Nullable<System.DateTime> FM { get; set; }
        public string UM { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public string UB { get; set; }
        public bool ST { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
