//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChkListCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.CursoXempleado = new HashSet<CursoXempleado>();
        }
    
        public int idCurso { get; set; }
        public System.Guid UuidCurso { get; set; }
        public string NombreCurso { get; set; }
        public System.Guid UuidInstructor { get; set; }
        public int Capacidad { get; set; }
        public decimal Duracion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FG { get; set; }
        public string UG { get; set; }
        public Nullable<System.DateTime> FM { get; set; }
        public string UM { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public string UB { get; set; }
        public bool ST { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoXempleado> CursoXempleado { get; set; }
    }
}
