//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChkListCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Certificado = new HashSet<Certificado>();
            this.CursoXempleado = new HashSet<CursoXempleado>();
        }
    
        public int idEmpleado { get; set; }
        public System.Guid UuidEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public int NoEmpleado { get; set; }
        public System.Guid UuidArea { get; set; }
        public System.DateTime FG { get; set; }
        public string UG { get; set; }
        public Nullable<System.DateTime> FM { get; set; }
        public string UM { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public string UB { get; set; }
        public bool ST { get; set; }
        public System.Guid UuidUsuario { get; set; }
    
        public virtual cat_Area cat_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificado> Certificado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoXempleado> CursoXempleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
