//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChkListCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.Certificado = new HashSet<Certificado>();
            this.Curso = new HashSet<Curso>();
            this.CursoXempleado = new HashSet<CursoXempleado>();
        }
    
        public int idInstructor { get; set; }
        public System.Guid UuidInstructor { get; set; }
        public string NombreInstructor { get; set; }
        public int NoInstructor { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public System.DateTime FG { get; set; }
        public string UG { get; set; }
        public Nullable<System.DateTime> FM { get; set; }
        public string UM { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public string UB { get; set; }
        public bool ST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificado> Certificado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curso> Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoXempleado> CursoXempleado { get; set; }
    }
}
